### ISSUE TITLE
SearchApi source missing underscore

### ISSUE THREAD

**Issue by Rich5** [manticoresoftware/manticoresearch-typescript#7]
Versions:
manticoresearch-ts: v4.1.0
manticoresearch: v6.2.12

I think the SearchApi is sending the wrong payload to the `/search` endpoint for the source field. When I prepare a searchRequest like shown below: 

```
const results: SearchResponse =  await searchApi.search({
            index: "my_index",
            query: { query_string: "a query" },
            source: ["id", "title", "abstract"],
            highlight: { 
           
            },
 
        });
```

The payload that is sent (verified with wireshark) is :

`{"index":"my_index","query":{"query_string":"a query"},"source":["id", "title", "abstract"],"highlight":{"}}
`

But the backend doesn't restrict the response objects to only the source fields because the key is missing the underscore `_source` which causes larger than expected payloads to be returned in my case. I verified this with curl also. 

Changing the request to include the underscore works just fine though. 

```
const results: SearchResponse =  await searchApi.search({
            index: "my_index",
            query: { query_string: "a query" },
            _source: ["id", "title", "abstract"],
            highlight: { 
           
            },
 
        });
```
The only impact now is that typescript linters get upset and throw errors like this:
 
`Object literal may only specify known properties, but '_source' does not exist in type 'SearchRequest'. Did you mean to write 'source'?ts(2561)`

I just started using this library so maybe I'm just using the API incorrectly, but I didn't see this mentioned in the docs.

**Comment by Nick-S-2018** [comment]
The issue is fixed in the dev version of the client, so you can use it.  This fix will be included in the next release.

**Comment by Rich5** [comment]
Hi @Nick-S-2018 , 

I installed 

npm install manticoresearch-ts-dev

but still get a type error when building for production for _source.  This isn't a problem for dev, but building for prod throws this type error.

I can work around this, but wondering if I'm doing something obviously wrong?
